services:
  app1:
    image: "localhost/app1:0.0.1"
    environment:
      LDAP_URL: "ldap://ldap:389"
      REDIS_URL: "redis:6379"
    ports:
      - "8080:8080"
    command:
      - "/wait-for-it.sh"
      - "ldap:389"
      - "--"
      - "/app1"
    depends_on:
      - ldap
      - redis

  ldap:
    image: "osixia/openldap:1.5.0"
    container_name: ldap
    environment:
      LDAP_ORGANISATION: "海山商事"
      LDAP_DOMAIN: "umiyama.com"
      LDAP_ADMIN_PASSWORD: "admin"
    ports:
      - "389:389"
    volumes:
      - "ldap_data:/var/lib/ldap"
      - "ldap_config:/etc/ldap/slapd.d"

  redis:
    image: "redis:7.4.2-alpine"
    container_name: redis
    volumes:
      - "redis_data:/data"
    ports:
      - "6379:6379"

volumes:
  ldap_data:
  ldap_config:
  redis_data: